"""dada

Revision ID: d6426636c0e3
Revises: 
Create Date: 2024-03-06 14:29:19.531308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6426636c0e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EMPLOYEES')
    op.drop_table('class1')
    op.drop_table('EMPLOYEE')
    op.drop_table('empjob')
    op.drop_table('JOB')
    op.drop_table('movie_data')
    op.drop_table('mov_data')
    op.drop_table('whetherapi1')
    op.drop_table('moviess_data')
    op.drop_table('users_details')
    op.drop_table('movies_data')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    op.create_table('movies_data',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('year', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('director', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Rated', mysql.VARCHAR(length=225), nullable=True),
    sa.Column('Released', mysql.DATETIME(), nullable=True),
    sa.Column('Runtime', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Genre', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('BoxOffice', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_details',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moviess_data',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('year', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('director', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Rated', mysql.VARCHAR(length=225), nullable=True),
    sa.Column('Released', sa.DATE(), nullable=True),
    sa.Column('Runtime', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Genre', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('BoxOffice', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whetherapi1',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('city_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('region', mysql.TEXT(), nullable=True),
    sa.Column('country1', mysql.TEXT(), nullable=True),
    sa.Column('lat', mysql.FLOAT(), nullable=True),
    sa.Column('lon', mysql.FLOAT(), nullable=True),
    sa.Column('temp', mysql.FLOAT(), nullable=True),
    sa.Column('pressure', mysql.FLOAT(), nullable=True),
    sa.Column('humidity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_updated', mysql.DATETIME(), nullable=True),
    sa.Column('code', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('condition1', mysql.TEXT(), nullable=True),
    sa.Column('date_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mov_data',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('year', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('director', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Rated', mysql.VARCHAR(length=225), nullable=True),
    sa.Column('Released', mysql.VARCHAR(length=225), nullable=True),
    sa.Column('Runtime', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Genre', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('BoxOffice', mysql.VARCHAR(length=225), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_data',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('year', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('director', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Rated', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('Released', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('Runtime', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('Genre', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('BoxOffice', mysql.VARCHAR(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('JOB',
    sa.Column('employeeid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('emplastname', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('empfirstname', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('jobtitle', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('employeeid')
    )
    op.create_table('empjob',
    sa.Column('employeeid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('joiningdate', mysql.DATETIME(), nullable=True),
    sa.Column('teamname', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('employeeid')
    )
    op.create_table('EMPLOYEE',
    sa.Column('ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employeeid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('firstname', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('lastname', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('department', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('salary', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('joiningdate', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('class1',
    sa.Column('ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employeeid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('firstname', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('lastname', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('department', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('joiningdate', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('EMPLOYEES',
    sa.Column('ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employeeid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('firstname', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('lastname', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('department', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('salary', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###
